

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume2
  namespace: poc
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp3
  volumeMode: Filesystem

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: task-pv-pod
# spec:
#   volumes:
#     - name: task-pv-storage
#       hostPath: 
#         path: /mnt/data
#   containers:
#     - name: task-pv-container
#       image: nginx
#       ports:
#         - containerPort: 80
#           name: "http-server"
#       volumeMounts:
#         - mountPath: "/tmp-ng"
#           name: task-pv-storage